### PR TITLE
Added Canvas UI elements

### PR DESCRIPTION
**Pull request by Qamardeen**

### CODE REVIEW

**Comment by saad-script** [comment]
What exactly was added in this PR?
I see that you added Text Mesh Pro, which is already in Unity Projects by default. There is no need to add it again.
@Qamardeen

**Comment by Qamardeen** [comment]
A canvas + couple text boxes to make a basic diaglouge box

**Comment by Qamardeen** [comment]
I can stash my changes and work off new dev...didnt do too much...i see that there is a merge conflict

**Comment by saad-script** [comment]
> A canvas + couple text boxes to make a basic diaglouge box

So did you manually add TMP to the project, or was that done automatically?

**Comment by saad-script** [comment]
> I can stash my changes and work off new dev...didnt do too much...i see that there is a merge conflict

Yea that happened after I merged my branch. You can pull master and redo the changes. That should fix it.

**Comment by saad-script** [comment]
> > I can stash my changes and work off new dev...didnt do too much...i see that there is a merge conflict
> 
> Yea that happened after I merged my branch. You can pull master and redo the changes. That should fix it.

Nvm, after doing a bit of research, it turns out that that should not be included in version control. Ill make an update to the .gitignore to fix the conflict

**Comment by saad-script** [comment]
@Qamardeen I fixed the merge conflict, just waiting on you to answer [this question](https://github.com/Qamardeen/UnityVNEngine/pull/3/#issuecomment-1200334269)

**Review by saad-script — APPROVED** [review]
Ok, turns out that TMP makes you import it, when you use it for the first time.
Should be good to merge.

**Comment by saad-script** [comment]
I should mention that, I don't see anything in the scene. Did you forget to save the scene before committing?

**Comment by Qamardeen** [comment]
I did forget to save it...

**Comment by Qamardeen** [comment]
Will re commit

**Comment by Qamardeen** [comment]
Did you smget an empty scene called scenetest or something?

**Comment by saad-script** [comment]
> Did you smget an empty scene called scenetest or something?

No that was added by you in the initial commit. Both of the scenes are empty so feel free to work an either one and delete the other.

**Pull request merged**
